### ISSUE TITLE
Peer to Peer Review from Team-109-Taipans

### ISSUE THREAD

**Issue by temesghentekeste** [0prodigy/youtube-clone#2]
- The Html code was semantically arranged
- The usage of font-awesome was appropriate

- Errors on the page 
   - Navbar was not required; the page should only have a header  section as there is no menu on the actual youtube page.
- the width of the image of the related videos should be of the same width

Keep it up the good job.

**Comment by 0prodigy** [comment]
Hey, @temesghentekeste  thanks for your time. I looked at our code and made recommended and necessary changes needed.
